### ISSUE TITLE
Use more open data portals

### ISSUE THREAD

**Issue by briatte** [briatte/parlnet#8]
See
- [ ] [this issue](https://github.com/briatte/nationalrat/issues/1) for the Austrian lower chamber (XML/RSS, feeds)
- [ ] [this issue](https://github.com/briatte/parlement/issues/1) for the French lower chamber (XML/JSON dumps)
- [x] [this issue](https://github.com/briatte/parlamento/issues/1) for Italy (XML/RDF via SPARQL queries, dumps)
